import { Raleway } from "next/font/google";
import "./globals.css";

// Import Raleway from Google Fonts
const raleway = Raleway({
  variable: "--font-raleway", // Set a custom variable for Raleway
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Specify font weights to load
});

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>{children}</body>
    </html>
  );
}
